---

- name: apt install tools
  hosts: all
  become: true
  roles:
    - role: apt
      tags: apt

- name: vim config
  hosts: all
  #become: true
  roles:
    - role: vim
      tags: vim

- name: tmux config
  hosts: all
  roles:
    - role: tmux
      tags: tmux